name: Update Portfolio

on:
  schedule:
    - cron: '0 5 * * 1-5'   # 週一至週五 05:00 UTC (台灣時間 13:00)
    - cron: '30 13 * * 1-5' # 週一至週五 13:30 UTC (台灣時間 21:30)
  workflow_dispatch:        # 允許手動觸發

env:
  GIST_ID: ${{ secrets.GIST_ID }}
  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        
    - name: Update portfolio
      run: python -m stock_tracker portfolio
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}