name: Update Portfolio

on:
  schedule:
    - cron: '0 5 * * 1-5'   # 週一至週五 05:00 UTC (台灣時間 13:00)
    - cron: '30 13 * * 1-5' # 週一至週五 13:30 UTC (台灣時間 21:30)
  workflow_dispatch:        # 允許手動觸發

env:
  GIST_ID: ${{ secrets.GIST_ID }}
  GIST_TOKEN: ${{ secrets.GIST_TOKEN }}

jobs:
  update-portfolio:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        
    - name: Check environment
      run: |
        echo "Checking environment variables..."
        if [ -n "$GIST_ID" ]; then
          echo "GIST_ID is set"
        else
          echo "GIST_ID is not set"
        fi
        if [ -n "$GIST_TOKEN" ]; then
          echo "GIST_TOKEN is set"
        else
          echo "GIST_TOKEN is not set"
        fi
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        
    - name: Update portfolio
      run: |
        echo "Starting portfolio update..."
        python -m stock_tracker portfolio --debug
      env:
        GIST_ID: ${{ secrets.GIST_ID }}
        GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        PYTHONPATH: ${{ github.workspace }}/src
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: portfolio-logs
        path: |
          logs/*.log
          *.log